version: "3.8"

services:
  unic-backend:
    container_name: unic_backend_api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # ── Database ──
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UniClubDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
      - ConnectionStrings__MeetingRoomConnection=Server=sqlserver;Database=UniClubMeetingRoom;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;

      # ── JWT ──
      - Jwt__Key=${JWT_KEY:-mysupersecretkey_for_jwt_demo_purpose_1234567890}
      - Jwt__Issuer=SecureApi
      - Jwt__Audience=SecureApiUsers
      - Jwt__ExpireMinutes=60
      # ── Email ──
      - Email__SmtpServer=smtp.gmail.com
      - Email__SmtpPort=587
      - Email__Username=${EMAIL_USERNAME:-kientrung2004x@gmail.com}
      - Email__Password=${EMAIL_PASSWORD:-jsem gszr rrcu ktsn}
      - Email__FromEmail=${EMAIL_FROM:-kientrung2004x@gmail.com}
      - Email__FromName=Member Management System
      # ── Cloudinary ──
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD:-dfhshcbbi}
      - Cloudinary__ApiKey=${CLOUDINARY_KEY:-749487828838273}
      - Cloudinary__ApiSecret=${CLOUDINARY_SECRET:-YIwBIL-YPEZLv_FPMct2OSFfPj0}
      # ── Gemini AI ──
      - Gemini__ApiKey=${GEMINI_API_KEY:-AIzaSyDVZCXRfDQEs-Nia5xqYH3RclHVDHPXigc}
      - Gemini__Model=gemini-2.5-flash
      - Gemini__TimeoutSeconds=120
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - unic-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: unic_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - unic-backend
    networks:
      - unic-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: unic_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - unic-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

networks:
  unic-network:
    driver: bridge

volumes:
  sql_data:
